### ISSUE TITLE
Ghidra directory name in user's home directory

### ISSUE THREAD

**Issue by versex799** [zackelia/ghidra-dark#12]
I was recently asked to help troubleshoot why this script was not working correctly. When I attempted to install this on my Manjaro VM, using Ghidra version 9.2.3, I found that the home/{user}/.ghidra/ no longer contained .ghidra_version_PUBLIC. It appears that they have changed it to .ghidra_version_DEV. Now, this could simply be the fact that I got it from the Arch repo instead of installing it manually, however, it appears the same is true when installing this on Kali using Ghidra version 9.1. 

It was simple enough to resolve. I just needed to go to line 96 of install.py and change _PUBLIC to _DEV. However, it might be a good idea to add this in. Again, I do not know if this is version-dependent or if it is just certain installations. I can add some checks to the script to determine if the directory is _PUBLIC or _DEV with a pull request if you would like. 

For now, anyone who runs into an issue with the script being unable to locate /home/user/.ghidra/.ghidra_{version}_PUBLIC/preferences, you will want to navigate to /home/user/.ghidra/ and make see if you have .ghidra_9.2.3_PUBLIC or .ghidra_9.2.3_DEV. If you have _DEV, you can resolve the issue by opening install.py and changing line 96 from _PUBLIC to _DEV.

![image (17)](https://user-images.githubusercontent.com/59210966/119532815-3b508500-bd53-11eb-8ee3-f482967f8068.png)

**Comment by zackelia** [comment]
Sorry for the long delay, this is fixed now!
