### ISSUE TITLE
Cant get it to work ::CCC

### ISSUE THREAD

**Issue by TQMatvey** [zackelia/ghidra-dark#19]
PS C:\Users\mmat0\Desktop\ghidra-dark-main> python install.py --path 'C:\Program Files\GhidraDecompiler\'
Traceback (most recent call last):
  File "C:\Users\mmat0\Desktop\ghidra-dark-main\install.py", line 270, in <module>
    main(parser.parse_args())
  File "C:\Users\mmat0\Desktop\ghidra-dark-main\install.py", line 240, in main
    ghidra_version = get_ghidra_version(ghidra_install_path)
  File "C:\Users\mmat0\Desktop\ghidra-dark-main\install.py", line 96, in get_ghidra_version
    with open(properties_path, "r") as fp:
OSError: [Errno 22] Invalid argument: 'C:\\Program Files\\GhidraDecompiler"\\Ghidra\\application.properties'

Idk how to get it to work 
![image_2021-09-19_065705](https://user-images.githubusercontent.com/77576395/133911333-64e178ec-b8a6-444d-914d-c7cfad0d9b3b.png)

**Comment by zackelia** [comment]
I was able to replicate the issue when I use a path that ends in a backslash: `python install.py --path 'C:\Program Files\Ghidra\'`. You can see this behavior discussed on the Python issue tracker here: https://bugs.python.org/issue39845.

Is the command you pasted the exact one you used to get that error? Using a path that doesn't end with a backslash seems to work fine for me: `python install.py --path 'C:\Program Files\Ghidra'`.

**Comment by TQMatvey** [comment]
![Uploading Screenshot (7).png…](
![Screenshot (8)](https://user-images.githubusercontent.com/77576395/133946264-eec00fd5-6f15-4531-a1f2-797395e645f3.png)
)
Thanks!! everything works now, still some unredeable white places but its 99% better than the original haha, thank you for creating this sick dark mode :)
