### ISSUE TITLE
macOS Brew Install issues

### ISSUE THREAD

**Issue by EthanG45** [zackelia/ghidra-dark#20]
Hello having a similar looking issue to #19. I have Ghidra installed with Homebrew on macOS. Not sure where the `application.properties` file should be stored.

```zsh
Traceback (most recent call last):
  File "/Users/Ethan/Developer/Tools/ghidra-dark/install.py", line 270, in <module>
    main(parser.parse_args())
  File "/Users/Ethan/Developer/Tools/ghidra-dark/install.py", line 240, in main
    ghidra_version = get_ghidra_version(ghidra_install_path)
  File "/Users/Ethan/Developer/Tools/ghidra-dark/install.py", line 96, in get_ghidra_version
    with open(properties_path, "r") as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/bin/Ghidra/application.properties'
```

**Comment by zackelia** [comment]
Thanks for pointing this out! `brew` made a symlink for `ghidraRun` which caused the script to look in the wrong place for Ghidra files. If you pull the most recent commit, it will now resolve that symlink and it should work.

**Comment by EthanG45** [comment]
Thanks so much this fixed the issue, and the install worked!
