### ISSUE TITLE
kali 2021 issue 

### ISSUE THREAD

**Issue by alt3kx** [zackelia/ghidra-dark#22]
Sounds good  your dark theme , below some issues with default kali 2021
```
$ python3 install.py --path /usr/share/ghidra 
[../snip]
PermissionError: [Errno 13] Permission denied: '/usr/share/ghidra/flatlaf-0.43.jar'
                                                                                                                                                      
$ sudo python3 install.py --path /usr/share/ghidra 
[sudo] password for test: 
ERROR: Please open Ghidra at least once to fully install dark mode.
                                                                                                                                                      
``
After that I restarted my ghidra but was not applied theme...

**Comment by FrancescoLucarini** [comment]
Same issue

**Comment by FrancescoLucarini** [comment]
first I created a new project and then I loaded a file, opened in the code browser, saved the file and closed Ghidra, then I runned the  script without sudo(I am on Lubuntu)

**Comment by alt3kx** [comment]
Reading more in depth , I forget  to see the  "user"  options , seems to be OK now  with following options kali default 

`$ sudo python3 install.py --user alex --path /usr/share/ghidra`

![image](https://user-images.githubusercontent.com/3140111/137635277-b2667434-2ba5-434e-80a6-28ae52cb7a20.png)

/alt3kx
