### ISSUE TITLE
Comments color is unreadable

### ISSUE THREAD

**Issue by mrdc** [zackelia/ghidra-dark#23]
Hello,

Please, check the issue:
![image](https://user-images.githubusercontent.com/16876990/139070261-a92bd3d1-640d-4148-b423-2ae371ac7f34.png)

Comments are not so easy to read.

**Comment by euphxny** [comment]
Unfortunately, that's hardcoded. You can change it here if you're building Ghidra on your machine:
https://github.com/NationalSecurityAgency/ghidra/blob/766ff7f72e056f109ed3192b3c3333b80c9deb6c/Ghidra/Features/Base/src/main/java/ghidra/app/util/viewer/field/MemoryBlockStartFieldFactory.java#L44

**Comment by mrdc** [comment]
> You can change it here if you're building Ghidra on your machine:

Can we do it ghidra-way? With binary patching :)

**Comment by euphxny** [comment]
@mrdc I'm not sure how you'd like to execute that idea but if you don't want to build Ghidra on your machine [here's](https://github.com/eravonic/ghidra/releases) a modified and compiled version of the Features Base module which contains the part of code that's responsible for the memory block color. Just replace it with the one in "[ghidra-dir]/Ghidra/Features/Base/lib/". (This is to be used with the 10.0.4 public build)

To get it to work you either update _preferences.py_ if you haven't installed ghidra-dark by adding this under "Listing Display":

![image](https://user-images.githubusercontent.com/86866731/141529865-5dc7511a-e856-4254-86f1-dc9825ed30ac.png)

Or if you already have ghidra-dark installed, you can edit your existing __code_browser.tcd_:

![image](https://user-images.githubusercontent.com/86866731/141529967-4a7c315e-3315-4088-b737-06c469f91693.png)

Here is the fork and edits of the compiled version if you're interested in what exactly I changed:
https://github.com/eravonic/ghidra/commit/1ba52cc391be6b973167e7e9fa53a5e4e31bbf2f

This is what it looks like after the edit:

![image](https://user-images.githubusercontent.com/86866731/141530338-23d004d6-8d3b-49a6-b332-ca71bc9f3019.png)

Of course, you can change the color to your liking.

**Comment by zackelia** [comment]
Same as #24, I will look into this again should this value stop being hardcoded one day.
