### ISSUE TITLE
Some windows are missing dark theme

### ISSUE THREAD

**Issue by mrdc** [zackelia/ghidra-dark#24]
Hello,

There are small issues with theme (missing dark theme): 

```
Window -> Bookmarks
Window -> Bytes
Window -> Bundle Manager
Window -> Comments
Window -> Data Type Manager
Window -> Defined Data
Window -> Defined Strings
Window -> Disassembled View
Window -> Functions
Window -> Memory Map
Window -> Relocation Table
Window -> Script Manager
Window -> Symbol References
Window -> Symbol Table

Graph -> Block Flow
Graph -> Code Flow
Graph -> Calls
```

**Comment by elbiazo** [comment]
![image](https://user-images.githubusercontent.com/23147879/140795760-3e626735-436f-41c6-a349-7eadde95d122.png)
Default Vertex Color and Graph Background Color is not set. This might be new because I don't remembering seeing this option in version 9

**Comment by zackelia** [comment]
Those graph color options are new/working in newer versions of Ghidra so I've added them to the script now. The other views all appear hardcoded to me but I will fix them if this changes in Ghidra. There at least seems to be some interest with the "Feature: GUI" label.
