### ISSUE TITLE
Some GUI elements are rendered unreadably

### ISSUE THREAD

**Issue by smithzvk** [zackelia/ghidra-dark#30]
This seems potentially related to #27, but it doesn't exactly look the same and the severity is quite a bit worse.  I see the color theme applied to almost all areas I care about, but certain areas become unusable, for example the strings tab, the script manager, the keybinding configuration dialog.  The text in these areas is rendered as slighly off-white against a white background.  I suspect that this is an issue due to the general dark OS theme... I don't know, I'm out of my depth on this one.

OS: Pop_OS 21.10
Ghidra: 10.1.2
ghidra-dark: ab7ca3302dd4a8b12c6e093d388e87c6d7e214d5

![image](https://user-images.githubusercontent.com/297543/158019316-9276bf43-e9a1-4909-baa9-626b9215b857.png)

![image](https://user-images.githubusercontent.com/297543/158019376-91b4fb4a-d803-42a7-a953-0072e88e9045.png)

![image](https://user-images.githubusercontent.com/297543/158019391-99934b35-a83f-4b05-859b-7d15d54790d1.png)

![image](https://user-images.githubusercontent.com/297543/158019439-19047235-f846-44d2-be17-6f6a629f8ca0.png)

![image](https://user-images.githubusercontent.com/297543/158019460-b746b823-2427-492e-aa43-fd7632202677.png)

**Comment by 1mansh0w** [comment]
Same on MacOS. When this gets fixed, it's the perfect theme. Thanks! :)

**Comment by SreeVathsan32** [comment]
Yeah please help to fix

**Comment by SiriusED** [comment]
Any fixes up?

**Comment by zackelia** [comment]
These places can not be fixed with a tool like `ghidra-dark` as the values of things such as table colors are hard coded in Ghidra itself. Not all hope is lost though! There is an open PR that integrates the existing color theme in this repo with some fixes for the views mentioned in this issue and others: https://github.com/NationalSecurityAgency/ghidra/pull/4145

**Comment by sr-tream** [comment]
@zackelia with this PR bug in function editor
![изображение](https://user-images.githubusercontent.com/12231048/172089018-ba2fd237-13c8-445d-bed1-d8153286f3a8.png)

**Comment by zackelia** [comment]
The PR I mentioned before did not achieve the results that I was hoping for in theming. If Ghidra is updated in the future to support these fixes I am willing to address.

**Comment by zackelia** [comment]
See #38 for some exciting developments!
