### ISSUE TITLE
Does not work with flatpak-installed Ghidra

### ISSUE THREAD

**Issue by mardab** [zackelia/ghidra-dark#31]
I know it's far from standard, but with --path set to user's mount of Ghidra ("~/.var/app/org.ghidra_sre.Ghidra/") script fails to see files that it needs, with errors such as
```FileNotFoundError: [Errno 2] No such file or directory: '/home/marcin/.var/app/org.ghidra_sre.Ghidra/Ghidra/application.properties'```

`application.properties` can be found at `~/.var/app/org.ghidra_sre.Ghidra/config`

**Comment by OTsector** [comment]
Hello,
In my case I have it done by this steps:
first search application properties path
`-[ In the kali linux I use: ```updatedb; locate application.properties|grep hidra```

output is: /usr/share/ghidra/Ghidra/application.properties

Next:
`-[ ```python install.py -u root --path=/usr/share/ghidra/```

Hope it's work!

**Comment by yassirlaaouissi** [comment]
i hope you dont ever consider flatpack anymore you soggy pancake

**Comment by ClaytonReardon** [comment]
@OTsector This doesn't seem to work for me, I get `ERROR: Please open Ghidra at least once to fully install dark mode.`
I have definitely opened ghidra at least once. Also running Kali.

**Comment by OTsector** [comment]
@Plus1059 I feel sorry can't help you.
please check another issue I have found. This is about your error: [https://github.com/zackelia/ghidra-dark/issues/22](https://github.com/zackelia/ghidra-dark/issues/22)
