### ISSUE TITLE
Question about setting color in other views

### ISSUE THREAD

**Issue by bruce30262** [zackelia/ghidra-dark#4]
Hello, thanks for the amazing project :)  

However I've found that some of the views aren't quite fit into the FlatLaf's dark theme.  

For example the function view:  

<img width="278" alt="func" src="https://user-images.githubusercontent.com/4478350/99350100-91da9380-28d8-11eb-9042-3c546306c2e7.PNG">
  
Defined string view:  

<img width="353" alt="str" src="https://user-images.githubusercontent.com/4478350/99350147-a4ed6380-28d8-11eb-8c34-33b6d8881867.PNG">

Script manager:  

<img width="473" alt="script" src="https://user-images.githubusercontent.com/4478350/99350162-ad459e80-28d8-11eb-8984-eab0d9648da1.PNG">

kind of hard to read the words in those views.  Anyway we could fix this ?

Also I would like to know if there's a way to change the font color in python interpreter / console ?  For now the font color is black and I would like to change that:

<img width="430" alt="py" src="https://user-images.githubusercontent.com/4478350/99350230-d1a17b00-28d8-11eb-885c-59f082dab61d.PNG">  

<img width="245" alt="consol" src="https://user-images.githubusercontent.com/4478350/99350234-d403d500-28d8-11eb-9c03-bb5a14b3c396.PNG">

**Comment by grant-h** [comment]
PCode is hard to read as well
![image](https://user-images.githubusercontent.com/3030665/99471501-877dc100-28fb-11eb-9eec-2137f109cb97.png)

**Comment by zackelia** [comment]
Thanks for the interest in the project! I have also noticed various places where the colors could be a bit better. Unfortunately, these colors are not available as configuration options and with at least the variables I checked in the source code, they are private, hard-coded values. Because of this, not even a plugin would be enough to fix them. I'm fairly certain that the only option here is to recompile Ghidra and take out/replace the hard coded values.

If it is of interest, I could possibly look into this and even provide a patched release if I can get it looking right. It would definitely be a little bit a time/work/research before I could get to that though.

**Comment by grant-h** [comment]
> Thanks for the interest in the project! I have also noticed various places where the colors could be a bit better. Unfortunately, these colors are not available as configuration options and with at least the variables I checked in the source code, they are private, hard-coded values. Because of this, not even a plugin would be enough to fix them. I'm fairly certain that the only option here is to recompile Ghidra and take out/replace the hard coded values.

I figured.

> If it is of interest, I could possibly look into this and even provide a patched release if I can get it looking right. It would definitely be a little bit a time/work/research before I could get to that though.

No need! We should report these bugs to upstream.

**Comment by grant-h** [comment]
Here are some relevant upstream issues:
* https://github.com/NationalSecurityAgency/ghidra/issues/1785
* https://github.com/NationalSecurityAgency/ghidra/issues/632#issuecomment-496629318

It looks like an official dark theme is on the road map, but not sure how long it would take.

Here is the hardcoded PCode field coloring:
* https://github.com/NationalSecurityAgency/ghidra/blob/27fb507b1877b13504baa75bc90da5f1db5f6ede/Ghidra/Features/Base/src/main/java/ghidra/app/util/pcode/PcodeFormatter.java#L102-L113

Here is a patch that fixes some of the panel's fg/bg coloring: https://github.com/pabx06/buildghidra/blob/8c75127ec14aaf9dadc963d9dfa8cc99ae24fff1/patch/InfoPanel.patch#L27

**Comment by CyberShadow** [comment]
An alternative approach (when it's available) is to use a pixel shader to invert the colors (optionally preserving hue).

There is some documentation on how to do it here:
https://github.com/vn971/linux-color-inversion

This avoids the issue with bright colors in other views, as well as issues with the FlatLaf skin (such as that scrolling while dragging doesn't work). It also allows color-keyed transparency.

How it looks for me right now (usable, though much room for improvement):

![](https://dump.cy.md/e569ba0564d16d4cf366fea16dc2e315/1615598296.187475200.png)
