### ISSUE TITLE
custom Ghidra home path

### ISSUE THREAD

**Issue by marius137** [zackelia/ghidra-dark#8]
I am using the AUR version of ghidra, so the ghidra path is `/opt/ghidra`, so the installer has to be ran as root (or sudo). 

The script takes the home path via `Path.home()` (line 99)  which is `/root` while it should be `/home/myUserName`

Edit: A hacky way to get it to install (in case you have the same problem) would be to hardcode the path in line 99 `ghidra_home_path = os.path.join("/home/myUserName", ".ghidra", version_path)`

**Comment by zackelia** [comment]
Thanks for the feedback! I've added a `--user` flag to specify which user you would like to install for.
